services:
  node-genai:
    build:
      context: ./node-genai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "172.17.0.1:host-gateway"
      # - "172.17.0.1:model-runner.docker.internal"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.17.0.1:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: hello-genai-network
    driver: bridge
