services:
  node-genai:
    build:
      context: ./node-genai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped

    # Mapear host.docker.internal al gateway del host
    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      # Ahora curl a host.docker.internal en lugar de la IP
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: hello-genai-network
    driver: bridge
